<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ9mSN5Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ9mSN5Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ9mSN5Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ9mSN5Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ9mSN5Y\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z9mSN5Y',
    'container.build_id' => '12208950',
    'container.build_time' => 1649142627,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ9mSN5Y');
