<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBIz75q1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBIz75q1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBIz75q1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBIz75q1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBIz75q1\App_KernelDevDebugContainer([
    'container.build_hash' => 'BIz75q1',
    'container.build_id' => '92c5281b',
    'container.build_time' => 1649056213,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBIz75q1');
