<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT68xLED\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT68xLED/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT68xLED.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT68xLED\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT68xLED\App_KernelDevDebugContainer([
    'container.build_hash' => 'T68xLED',
    'container.build_id' => '96dd2ff1',
    'container.build_time' => 1648812923,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT68xLED');
